service: amazon-bedrock-bot

# deployするのは、handler.js ファイルのみ
package:
  exclude:
    - node_modules/**
    - my-layer/**
    - .gitignore
    - .git/**
    - package-lock.json
    - package.json
    - README.md
    - event.json

provider:
  name: aws
  runtime: nodejs20.x
  profile: default
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  environment:
    CHANNEL_ACCESS_TOKEN: "YOUR LINE CHANNEL ACCESS TOKEN"
    CHANNEL_SECRET: "YOUR LINE CHANNEL ACCESS TOKEN"
    OPENAI_API_KEY: "YOUR OPENAI API KEY"
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}-conversations
    S3_BUCKET: ${self:service}-${self:provider.stage}-bucket
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "bedrock:InvokeModel"
        - "bedrock:ListFoundationModels"
      Resource: "arn:aws:bedrock:*:*:foundation-model/*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        - s3:ListBucket
        - s3:ListBucketMultipartUploads
        - s3:ListMultipartUploadParts
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"

functions:
  bot:
    handler: handler.callback
    layers:
      - arn:aws:lambda:ap-northeast-1:919605901492:layer:open-api-nodejs:4
    events:
      - http:
          path: callback
          method: post
          cors: true
          async: true
    timeout: 180
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

resources:
  Resources:
    ConversationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerPreferred
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
              AllowedOrigins:
                - "*"
    S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Bucket
                  - /*
    # ApiGatewayMethodPostTask:
    #   Type: AWS::ApiGateway::Method
    #   Properties:
    #     HttpMethod: POST
    #     ResourceId: 
    #       Ref: ApiGatewayResourceCallback
    #     RestApiId: 
    #       Ref: ApiGatewayRestApi
    #     AuthorizationType: NONE
    #     Integration:
    #       Type: AWS
    #       IntegrationHttpMethod: POST
    #       # arn:aws:lambda:ap-northeast-1:919605901492:function:aws-node-line-bot-dev-bot
    #       Uri: arn:aws:apigateway:${self:provider.region}:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:919605901492:function:aws-node-line-bot-${self:provider.stage}-bot/invocations
    #       IntegrationResponses:
    #         - StatusCode: 202
    #     MethodResponses:
    #       - StatusCode: 202